In [38]:
import pandas as pd
df = pd.read_csv(r'F:\Rehab work\NFL Hackathon\Raw Data\nfl-big-data-bowl-2027\players.csv')
df

,nfl_id,display_name,draft_year,nfl_position,birth_date,college_name,college_conference,draft_round,draft_pick_within_round,draft_overall_pick
0,55867,Will Anderson,2023,DE,2001-09-02,Alabama,Southeastern Conference,1.0,3.0,3.0
1,55870,Paris Johnson,2023,T,2001-07-31,Ohio State,Big Ten Conference,1.0,6.0,6.0
2,55874,Darnell Wright,2023,T,2001-08-10,Tennessee,Southeastern Conference,1.0,10.0,10.0
3,55875,Peter Skoronski,2023,G,2001-07-31,Northwestern,Big Ten Conference,1.0,11.0,11.0
4,55877,Lukas Van Ness,2023,DE,2001-07-06,Iowa,Big Ten Conference,1.0,13.0,13.0
...,...,...,...,...,...,...,...,...,...,...
505,58883,Antwane Wells,2025,WR,2001-04-02,Mississippi,Southeastern Conference,NaN,NaN,NaN
506,59000,Malik Verdon,2025,ILB,2002-10-31,Iowa State,Big Twelve Conference,NaN,NaN,NaN
507,58476,Hollin Pierce,2025,T,2000-04-19,Rutgers,Big Ten Conference,NaN,NaN,NaN
508,58968,Xavier Restrepo,2025,WR,2002-04-12,Miami,Atlantic Coast Conference,NaN,NaN,NaN
509,58494,Josh Kelly,2025,WR,2001-07-01,Texas Tech,Big Twelve Conference,NaN,NaN,NaN

In [39]:
df.shape

(510, 10)

In [40]:
df.columns.tolist()

['nfl_id',
 'display_name',
 'draft_year',
 'nfl_position',
 'birth_date',
 'college_name',
 'college_conference',
 'draft_round',
 'draft_pick_within_round',
 'draft_overall_pick']

In [41]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   nfl_id                   510 non-null    int64
 1   display_name             510 non-null    str
 2   draft_year               510 non-null    int64
 3   nfl_position             510 non-null    str
 4   birth_date               510 non-null    str
 5   college_name             510 non-null    str
 6   college_conference       510 non-null    str
 7   draft_round              383 non-null    float64
 8   draft_pick_within_round  383 non-null    float64
 9   draft_overall_pick       383 non-null    float64
dtypes: float64(3), int64(2), str(5)
memory usage: 170.4 KB

In [42]:
from IPython.display import display

display(df.head())
display(df.sample(5, random_state=46))

,nfl_id,display_name,draft_year,nfl_position,birth_date,college_name,college_conference,draft_round,draft_pick_within_round,draft_overall_pick
0,55867,Will Anderson,2023,DE,2001-09-02,Alabama,Southeastern Conference,1.0,3.0,3.0
1,55870,Paris Johnson,2023,T,2001-07-31,Ohio State,Big Ten Conference,1.0,6.0,6.0
2,55874,Darnell Wright,2023,T,2001-08-10,Tennessee,Southeastern Conference,1.0,10.0,10.0
3,55875,Peter Skoronski,2023,G,2001-07-31,Northwestern,Big Ten Conference,1.0,11.0,11.0
4,55877,Lukas Van Ness,2023,DE,2001-07-06,Iowa,Big Ten Conference,1.0,13.0,13.0

,nfl_id,display_name,draft_year,nfl_position,birth_date,college_name,college_conference,draft_round,draft_pick_within_round,draft_overall_pick
115,56121,Grant DuBose,2023,WR,2001-06-20,North Carolina-Charlotte,American Athletic Conference,7.0,39.0,256.0
252,57284,Jacob Monk,2024,C,2001-06-04,Duke,Atlantic Coast Conference,5.0,28.0,163.0
437,58403,Warren Brinson,2025,DT,2002-02-04,Georgia,Southeastern Conference,6.0,22.0,198.0
55,55976,Dawand Jones,2023,T,2001-08-06,Ohio State,Big Ten Conference,4.0,9.0,111.0
227,57232,Evan Williams,2024,FS,2001-07-28,Oregon,Pacific Twelve Conference,4.0,11.0,111.0

In [43]:
df.index

RangeIndex(start=0, stop=510, step=1)

### Check Column Name Consistency

In [44]:
for col in df.columns:
    print(repr(col))

'nfl_id'
'display_name'
'draft_year'
'nfl_position'
'birth_date'
'college_name'
'college_conference'
'draft_round'
'draft_pick_within_round'
'draft_overall_pick'

In [45]:
structural_summary = pd.DataFrame({
    "column_name": df.columns,
    "data_type": df.dtypes.astype(str).values
})

structural_summary

               column_name data_type
0                   nfl_id     int64
1             display_name       str
2               draft_year     int64
3             nfl_position       str
4               birth_date       str
5             college_name       str
6       college_conference       str
7              draft_round   float64
8  draft_pick_within_round   float64
9       draft_overall_pick   float64

### Missing Value Analysis

In [46]:
df.isnull().sum()

nfl_id                       0
display_name                 0
draft_year                   0
nfl_position                 0
birth_date                   0
college_name                 0
college_conference           0
draft_round                127
draft_pick_within_round    127
draft_overall_pick         127
dtype: int64

In [47]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

nfl_id                      0.000000
display_name                0.000000
draft_year                  0.000000
nfl_position                0.000000
birth_date                  0.000000
college_name                0.000000
college_conference          0.000000
draft_round                24.901961
draft_pick_within_round    24.901961
draft_overall_pick         24.901961
dtype: float64

In [48]:
missing_summary = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percentage": df.isna().mean() * 100
})

missing_summary = missing_summary.sort_values(
    by="missing_percentage",
    ascending=False
)

missing_summary

                         missing_count  missing_percentage
draft_overall_pick                 127           24.901961
draft_pick_within_round            127           24.901961
draft_round                        127           24.901961
nfl_id                               0            0.000000
display_name                         0            0.000000
draft_year                           0            0.000000
college_name                         0            0.000000
birth_date                           0            0.000000
nfl_position                         0            0.000000
college_conference                   0            0.000000

In [49]:
draft_cols = [
    "draft_round",
    "draft_pick_within_round",
    "draft_overall_pick"
]

df[draft_cols].isna().value_counts()

draft_round  draft_pick_within_round  draft_overall_pick
False        False                    False                 383
True         True                     True                  127
Name: count, dtype: int64

In [50]:
df.loc[
    df["draft_round"].isna(),
    "draft_year"
].isna().value_counts()

draft_year
False    127
Name: count, dtype: int64

### Add new Feature "draft_status"

In [51]:
import numpy as np

df["draft_status"] = np.where(
    df["draft_round"].isna(),
    "Undrafted",
    "Drafted"
)

In [52]:
df["draft_status"].value_counts()

draft_status
Drafted      383
Undrafted    127
Name: count, dtype: int64

### Data Quality Finding — Draft Attributes

**Observation:** 127 out of 510 players (24.9%) have missing values in `draft_round`, `draft_pick_within_round`, and `draft_overall_pick`.

**Root Cause:** According to the Kaggle Data Dictionary, these missing values indicate undrafted players.

**Missingness Type:** Structural Missingness (Not Applicable).

**Decision:**
- Preserve NULL values in the original draft-related columns.
- Do not apply mean, median, or zero imputation.
- Create a derived `draft_status` feature during preprocessing if needed.

**Data Quality Status:** Expected missingness — no corrective action required.

In [53]:
df.duplicated().sum()

np.int64(0)

In [54]:
df["nfl_id"].duplicated().sum()

np.int64(0)

In [55]:
df["nfl_id"].is_unique

True

### Draft Round Distribution Analysis

**Objective:** Analyze the distribution of players across NFL Draft rounds and identify undrafted players.

**Code Explanation:**
- `value_counts()` counts the number of players in each draft round.
- `dropna=False` includes missing values (NULL), which represent undrafted players in this dataset.
- `sort_index()` sorts the results by draft round in ascending order.

**Expected Output:** The number of players selected in each draft round (1–7), along with the number of undrafted players.

**Purpose:** Understand the distribution of drafted and undrafted players and identify any unexpected draft round values.

In [56]:
df["draft_round"].value_counts(dropna=False).sort_index()

draft_round
1.0     38
2.0     59
3.0     59
4.0     59
5.0     62
6.0     50
7.0     56
NaN    127
Name: count, dtype: int64

### Draft Round Distribution — Findings

- The dataset contains 510 players: 383 drafted (75.1%) and 127 undrafted (24.9%).
- All non-null draft rounds fall within the valid NFL range of 1–7.
- Round 5 has the highest number of drafted players (62), while Round 1 has the lowest (38).
- Missing draft-round values represent undrafted players, according to the dataset documentation.

**Data Quality Conclusion:** No invalid draft-round values were identified. The missing values are expected and should be preserved.

### Draft Year Distribution Analysis

**Objective:** Examine the distribution of players by NFL Draft year and validate that all values fall within the expected range (2023–2025).

**Code Explanation:**
- `value_counts(dropna=False)` counts players for each draft year, including missing values.
- `sort_index()` sorts the results chronologically.

**Purpose:** Identify unexpected years, missing values, and differences in player counts across draft classes.

In [57]:
df["draft_year"].value_counts(dropna=False).sort_index()

draft_year
2023    160
2024    177
2025    173
Name: count, dtype: int64

### Draft Year Distribution — Findings

- All 510 players have a valid `draft_year` (2023, 2024, or 2025).
- No missing or unexpected draft-year values were identified.
- The distribution is relatively balanced across the three draft classes:
  - 2023: 160 players (31.37%)
  - 2024: 177 players (34.71%)
  - 2025: 173 players (33.92%)

**Data Quality Conclusion:** The `draft_year` column is complete and contains only expected values.

### Draft Pick Range Validation

**Objective:** Validate the minimum and maximum values of draft pick positions and identify potentially invalid values.

**Columns:**
- `draft_pick_within_round`: The player's selection order within a specific draft round.
- `draft_overall_pick`: The player's selection order across the entire NFL Draft.

**Validation Rules:**
- Non-null draft picks must be positive integers.
- Missing values represent undrafted players.
- The overall pick should not be smaller than the pick within the round.

**Purpose:** Identify invalid draft pick positions and potential inconsistencies before preprocessing.

In [58]:
draft_pick_cols = [
    "draft_pick_within_round",
    "draft_overall_pick"
]

df[draft_pick_cols].agg(["min", "max"])

     draft_pick_within_round  draft_overall_pick
min                      1.0                 3.0
max                     43.0               257.0

### Draft Pick Consistency Validation

**Objective:** Verify the logical consistency between draft round, pick within round, and overall draft pick.

**Validation Rules:**
- Drafted players must have complete draft selection information.
- Draft pick values must be positive integers.
- `draft_overall_pick` must be greater than or equal to `draft_pick_within_round`.
- For Round 1, the overall pick should equal the pick within the round.

**Purpose:** Detect inconsistent draft selection records before data preprocessing.

In [59]:
drafted = df[df["draft_round"].notna()]

invalid_picks = drafted[
    (
        drafted["draft_overall_pick"]
        < drafted["draft_pick_within_round"]
    )
    |
    (
        (drafted["draft_round"] == 1)
        &
        (
            drafted["draft_overall_pick"]
            != drafted["draft_pick_within_round"]
        )
    )
]

print("Invalid Draft Picks:", len(invalid_picks))

invalid_picks[
    [
        "display_name",
        "draft_round",
        "draft_pick_within_round",
        "draft_overall_pick"
    ]
]

Invalid Draft Picks: 4

        display_name  draft_round  draft_pick_within_round  draft_overall_pick
8   Quentin Johnston          1.0                     22.0                21.0
9     Jordan Addison          1.0                     24.0                23.0
10      Deonte Banks          1.0                     25.0                24.0
11    Anton Harrison          1.0                     28.0                27.0

### Investigation of Draft Pick Inconsistencies

**Objective:** Investigate four first-round draft records where `draft_pick_within_round` differs from `draft_overall_pick`.

**Initial Finding:** Four records show a difference of exactly one pick.

**Next Action:** Examine the draft year and pick values to determine whether these differences reflect the dataset's numbering convention or actual data errors.

**Data Quality Status:** Potential inconsistency — requires validation before correction.

In [60]:
invalid_picks[
    [
        "display_name",
        "draft_year",
        "draft_round",
        "draft_pick_within_round",
        "draft_overall_pick"
    ]
]

,display_name,draft_year,draft_round,draft_pick_within_round,draft_overall_pick
8,Quentin Johnston,2023,1.0,22.0,21.0
9,Jordan Addison,2023,1.0,24.0,23.0
10,Deonte Banks,2023,1.0,25.0,24.0
11,Anton Harrison,2023,1.0,28.0,27.0

### Data Quality Finding — Draft Pick Numbering Inconsistency

**Finding:** Four players from the 2023 first round have inconsistent values between `draft_pick_within_round` and `draft_overall_pick`.

**Observed Pattern:** The within-round pick number exceeds the overall pick number by exactly one.

**Expected Behavior:** According to the dataset's column definitions, first-round pick positions should match their overall draft selection numbers.

**Data Quality Status:** Potential data inconsistency — external verification required.

**Recommended Action:** Compare the affected records against the official 2023 NFL Draft results. Preserve the original values until the correct numbering convention is confirmed.

### Uniqueness and Duplicate Validation

**Objective:** Identify duplicate records and validate the uniqueness of player identifiers.

**Validation Checks:**
- Detect fully duplicated rows.
- Check for duplicate `nfl_id` values.
- Verify that `nfl_id` contains no missing values.
- Determine whether `nfl_id` can serve as a primary key.

**Purpose:** Ensure player-level data integrity and prevent duplicate records from causing incorrect results during joins with other NFL datasets.

print("Duplicate Rows:", df.duplicated().sum())

print("Duplicate NFL IDs:", df["nfl_id"].duplicated().sum())

print("Missing NFL IDs:", df["nfl_id"].isna().sum())

print("Is NFL ID Unique?", df["nfl_id"].is_unique)

In [61]:
print("Duplicate Rows:", df.duplicated().sum())

print("Duplicate NFL IDs:", df["nfl_id"].duplicated().sum())

print("Missing NFL IDs:", df["nfl_id"].isna().sum())

print("Is NFL ID Unique?", df["nfl_id"].is_unique)

Duplicate Rows: 0
Duplicate NFL IDs: 0
Missing NFL IDs: 0
Is NFL ID Unique? True

### Birth Date Validation

**Objective:** Assess the completeness, data type, and validity of the `birth_date` column.

**Validation Checks:**
- Count missing birth dates.
- Inspect the current data type.
- Convert values to datetime for validation without modifying the original dataset.
- Identify invalid or unparseable date values.

**Purpose:** Ensure that player birth dates are reliable for future age-related analysis and feature engineering.

In [62]:
# Check missing values
print("Missing Birth Dates:", df["birth_date"].isna().sum())

# Check current data type
print("Birth Date Data Type:", df["birth_date"].dtype)

# Convert to datetime for validation
birth_dates = pd.to_datetime(
    df["birth_date"],
    errors="coerce"
)

# Check invalid dates (excluding original missing values)
invalid_dates = (
    df["birth_date"].notna() &
    birth_dates.isna()
)

print("Invalid Birth Dates:", invalid_dates.sum())

# Check date range
print("Earliest Birth Date:", birth_dates.min())
print("Latest Birth Date:", birth_dates.max())

Missing Birth Dates: 0
Birth Date Data Type: str
Invalid Birth Dates: 0
Earliest Birth Date: 1997-12-12 00:00:00
Latest Birth Date: 2004-08-25 00:00:00

### Birth Date Validation — Findings

- All 510 players have non-null birth dates.
- No invalid or unparseable dates were detected.
- The earliest birth date is December 12, 1997.
- The latest birth date is August 25, 2004.
- The original `birth_date` column is stored as a string.

**Data Quality Conclusion:** Birth dates are complete and parseable. Date conversion is recommended during preprocessing, and player age plausibility should be validated before using age-related features.

### Player Age Plausibility Validation

**Objective:** Evaluate whether players' birth dates are plausible relative to their NFL Draft year.

**Method:** Calculate an approximate draft-year age by subtracting the birth year from the draft year.

**Validation:** Flag players whose approximate age falls outside an exploratory range of 18–30 years.

**Purpose:** Identify potentially unrealistic birth dates or draft-year values requiring further investigation.

**Note:** The age range is an initial profiling threshold, not an official NFL eligibility rule. Flagged records require review rather than automatic removal.

In [63]:
# Calculate approximate age during draft year
approx_draft_age = (
    df["draft_year"] - birth_dates.dt.year
)

# Check age distribution
print(approx_draft_age.describe())

# Identify potentially unrealistic ages
invalid_age_mask = (
    (approx_draft_age < 18) |
    (approx_draft_age > 30)
)

print("Potentially Unrealistic Ages:", invalid_age_mask.sum())

# Display flagged records
df.loc[
    invalid_age_mask,
    ["display_name", "birth_date", "draft_year"]
]

count    510.000000
mean      23.105882
std        1.052905
min       21.000000
25%       22.000000
50%       23.000000
75%       24.000000
max       27.000000
dtype: float64
Potentially Unrealistic Ages: 0

Empty DataFrame
Columns: [display_name, birth_date, draft_year]
Index: []

### Player Age Plausibility — Findings

- Approximate draft-year age was calculated for all 510 players.
- The average approximate age is 23.11 years, with a standard deviation of 1.05.
- Player ages range from 21 to 27 years.
- The median approximate age is 23 years.
- No players fall outside the exploratory plausibility range of 18–30 years.

**Data Quality Conclusion:** No implausible ages were identified using the selected validation threshold. Birth dates appear suitable for age-related analysis, subject to any further source-level validation.

### NFL Position Distribution & Validation

**Objective:** Analyze the distribution of NFL player positions and assess the completeness and consistency of the `nfl_position` column.

**Validation Checks:**
- Count players in each NFL position.
- Identify missing position values.
- Detect inconsistent position labels caused by whitespace or capitalization.
- Determine the number of Wide Receivers (WR) available for the project.

**Purpose:** Validate position-level data quality and assess the representation of Wide Receivers in the dataset.

In [64]:
# Position distribution
print("Position Distribution:")
print(df["nfl_position"].value_counts(dropna=False))

# Missing positions
print("\nMissing Positions:",
      df["nfl_position"].isna().sum())

# Unique positions
print("\nUnique Positions:")
print(sorted(df["nfl_position"].dropna().unique()))

# Check inconsistent formatting
position_clean = df["nfl_position"].str.strip().str.upper()

format_issues = (
    df["nfl_position"].notna() &
    df["nfl_position"].ne(position_clean)
)

print("\nPosition Formatting Issues:",
      format_issues.sum())

# Count Wide Receivers
print("\nTotal WR Players:",
      (position_clean == "WR").sum())

Position Distribution:
nfl_position
WR     106
CB      60
G       51
T       50
DT      47
TE      42
DE      36
OLB     30
SS      28
FS      25
C       20
NT       5
DB       5
ILB      2
RB       1
MLB      1
FB       1
Name: count, dtype: int64

Missing Positions: 0

Unique Positions:
['C', 'CB', 'DB', 'DE', 'DT', 'FB', 'FS', 'G', 'ILB', 'MLB', 'NT', 'OLB', 'RB', 'SS', 'T', 'TE', 'WR']

Position Formatting Issues: 0

Total WR Players: 106

### NFL Position Distribution — Findings

- The dataset contains 17 distinct NFL positions.
- No missing values or formatting inconsistencies were detected in `nfl_position`.
- Wide Receiver (WR) is the most represented position, with 106 players (20.78% of the dataset).
- Quarterback (QB) is not represented in the player records.
- Position labels appear consistent based on the performed formatting checks.

**Data Quality Conclusion:** No missing or formatting-related issues were detected in the `nfl_position` column. The dataset contains 106 WR players for further analysis.

**Next Validation:** Verify WR player coverage across `player_play` and `game_tracking` before determining the final analysis population.

### College Information — Completeness & Consistency Validation

**Objective:** Assess the completeness and formatting consistency of college-related attributes.

**Columns:**
- `college_name`: College or university attended by the player.
- `college_conference`: Athletic conference associated with the player's college.

**Validation Checks:**
- Count missing values in both columns.
- Identify blank strings and whitespace-only values.
- Detect leading/trailing spaces and inconsistent capitalization.
- Examine the most frequently represented colleges and conferences.

**Purpose:** Identify missing or inconsistent college information and determine whether additional cleaning is required.

In [65]:
college_cols = ["college_name", "college_conference"]

# 1. Missing values
print("Missing Values:")
print(df[college_cols].isna().sum())

# 2. Blank or whitespace-only strings
print("\nBlank Values:")
print(
    df[college_cols]
    .apply(lambda col: col.str.strip().eq("").sum())
)

# 3. Leading/trailing spaces
print("\nWhitespace Issues:")
print(
    df[college_cols].apply(
        lambda col: (
            col.notna() &
            col.ne(col.str.strip())
        ).sum()
    )
)

# 4. Most frequent colleges
print("\nTop 10 Colleges:")
print(df["college_name"].value_counts().head(10))

# 5. Conference distribution
print("\nCollege Conference Distribution:")
print(df["college_conference"].value_counts(dropna=False))

Missing Values:
college_name          0
college_conference    0
dtype: int64

Blank Values:
college_name          0
college_conference    0
dtype: int64

Whitespace Issues:
college_name          0
college_conference    0
dtype: int64

Top 10 Colleges:
college_name
Georgia            22
Alabama            16
Louisiana State    15
Ohio State         14
South Carolina     14
Texas              14
Michigan           12
Maryland           11
Mississippi        11
Florida            11
Name: count, dtype: int64

College Conference Distribution:
college_conference
Southeastern Conference                            142
Big Ten Conference                                  96
Atlantic Coast Conference                           81
Big Twelve Conference                               71
Pacific Twelve Conference                           44
Independent                                         14
American Athletic Conference                        14
Mountain West Conference                            10
Mid-American Conference                              8
Missouri Valley Football Conference                  6
Conference USA                                       6
Sun Belt Conference                                  6
Southwestern Athletic Conference                     3
Patriot League                                       2
Ivy League                                           1
Great Lakes Intercollegiate Athletic Conference      1
Southern Conference                                  1
Southland Conference                                 1
Big South - Ohio Valley Conference                   1
Mid-Eastern Athletic Conference                      1
United Athletic Conference                           1
Name: count, dtype: int64

### College Information Validation — Findings

- No missing values were detected in `college_name` or `college_conference`.
- No blank or whitespace-only values were identified.
- No leading or trailing whitespace issues were detected.
- Georgia is the most represented college, with 22 players, followed by Alabama (16) and Louisiana State (15).
- College and conference distributions were examined to understand player representation across educational institutions.

**Data Quality Conclusion:** Both college-related columns passed the completeness and whitespace validation checks. Further consistency checks may be needed to identify naming variations or inconsistent college-to-conference mappings.

### College-to-Conference Consistency Validation

**Objective:** Identify colleges associated with multiple conference names in the dataset.

**Method:** Count the number of distinct conference values associated with each college.

**Purpose:** Detect potential inconsistencies in college-to-conference mappings.

**Note:** Multiple conferences for the same college do not automatically indicate an error, as conference membership can change over time.

In [66]:
college_conference_check = (
    df.groupby("college_name")["college_conference"]
    .nunique()
    .sort_values(ascending=False)
)

print("Colleges with Multiple Conferences:")

print(college_conference_check[college_conference_check > 1])

Colleges with Multiple Conferences:
college_name
Arizona                2
California             2
Brigham Young          2
Cincinnati             2
Houston                2
Oregon                 2
Rice                   2
UCLA                   2
Southern Methodist     2
Southern California    2
Texas                  2
Stanford               2
Utah                   2
Oklahoma               2
Name: college_conference, dtype: int64

### Investigation of Multiple College Conference Associations

**Objective:** Investigate the 14 colleges associated with more than one conference.

**Method:** Examine each college's conference names and the draft years in which they appear.

**Purpose:** Determine whether multiple conference associations reflect historical conference realignment, inconsistent naming, or potential data quality issues.

**Data Quality Status:** Under investigation. No changes will be made to the original data until the differences are understood.

### College-to-Conference Consistency Investigation

**Objective:** Investigate colleges associated with multiple athletic conferences.

**Initial Finding:** 14 colleges are associated with two distinct conference names.

**Method:** Examine conference names and draft years for each affected college.

**Purpose:** Determine whether the differences reflect historical conference realignment, inconsistent naming, or potential data quality issues.

**Note:** Multiple conference associations do not automatically indicate incorrect data. Original values will be preserved until the findings are verified.

In [68]:
# Get colleges associated with multiple conferences
multiple_conference_colleges = (
    college_conference_check[
        college_conference_check > 1
    ].index
)

# Examine conference associations by draft year
conference_details = (
    df[df["college_name"].isin(multiple_conference_colleges)]
    .groupby([
        "college_name",
        "draft_year",
        "college_conference"
    ])
    .size()
    .reset_index(name="player_count")
    .sort_values([
        "college_name",
        "draft_year",
        "college_conference"
    ])
)

conference_details

,college_name,draft_year,college_conference,player_count
0,Arizona,2024,Big Twelve Conference,1
1,Arizona,2024,Pacific Twelve Conference,1
2,Arizona,2025,Big Twelve Conference,1
3,Brigham Young,2023,Independent,2
4,Brigham Young,2024,Big Twelve Conference,1
5,Brigham Young,2025,Big Twelve Conference,1
6,California,2023,Pacific Twelve Conference,1
7,California,2024,Pacific Twelve Conference,1
8,California,2025,Atlantic Coast Conference,2
9,Cincinnati,2023,American Athletic Conference,4
10,Cincinnati,2023,Big Twelve Conference,1
11,Cincinnati,2025,Big Twelve Conference,1
12,Houston,2023,American Athletic Conference,2
13,Houston,2024,Big Twelve Conference,2
14,Oklahoma,2023,Big Twelve Conference,4
15,Oklahoma,2024,Big Twelve Conference,2
16,Oklahoma,2025,Southeastern Conference,2
17,Oregon,2023,Pacific Twelve Conference,1
18,Oregon,2024,Pacific Twelve Conference,4
19,Oregon,2025,Big Ten Conference,6
20,Rice,2023,Conference USA,1
21,Rice,2024,American Athletic Conference,1
22,Southern California,2023,Pacific Twelve Conference,2
23,Southern California,2024,Big Ten Conference,1
24,Southern California,2024,Pacific Twelve Conference,5
25,Southern California,2025,Big Ten Conference,1
26,Southern Methodist,2023,American Athletic Conference,1
27,Southern Methodist,2025,Atlantic Coast Conference,1
28,Stanford,2023,Pacific Twelve Conference,2
29,Stanford,2025,Atlantic Coast Conference,1
30,Texas,2023,Big Twelve Conference,1
31,Texas,2024,Big Twelve Conference,6
32,Texas,2025,Southeastern Conference,7
33,UCLA,2023,Pacific Twelve Conference,2
34,UCLA,2024,Pacific Twelve Conference,1
35,UCLA,2025,Big Ten Conference,2
36,Utah,2023,Pacific Twelve Conference,2
37,Utah,2024,Pacific Twelve Conference,5
38,Utah,2025,Big Twelve Conference,1

### College-to-Conference Consistency — Findings

- 14 colleges are associated with two distinct conference names.
- Several conference changes are consistent with historical college football realignment, including Oregon, Texas, Oklahoma, and UCLA.
- Three colleges have multiple conference associations within the same draft year: Arizona (2024), Cincinnati (2023), and Southern California (2024).
- Same-year differences require further investigation because draft year does not necessarily represent the college season or conference membership date.

**Data Quality Status:** Potential temporal consistency issues; no confirmed errors.

**Recommended Action:** Preserve the original conference values and document the need to verify their temporal meaning before using conference-related features in modeling.

### Wide Receiver (WR) — Draft Year Distribution

**Objective:** Analyze the distribution of Wide Receivers across the 2023–2025 NFL Draft classes.

**Method:** Filter the player dataset to the WR position and count players by draft year.

**Purpose:** Understand the composition of the WR population and establish a baseline for subsequent cross-table coverage analysis.

In [69]:
# Filter Wide Receivers
wr_players = df[
    df["nfl_position"] == "WR"
].copy()

# Total unique WR players
print("Total WR Players:",
      wr_players["nfl_id"].nunique())

# WR distribution by draft year
print("\nWR Distribution by Draft Year:")
print(
    wr_players["draft_year"]
    .value_counts()
    .sort_index()
)

Total WR Players: 106

WR Distribution by Draft Year:
draft_year
2023    38
2024    31
2025    37
Name: count, dtype: int64

### WR Draft Status Analysis

**Objective:** Analyze the distribution of drafted and undrafted Wide Receivers.

**Method:** Classify WR players based on the availability of `draft_round`.

- **Drafted:** Players with a non-null `draft_round`.
- **Undrafted:** Players with a null `draft_round`.

**Purpose:** Understand the draft composition of the WR population and identify expected missing values in draft-related attributes.

**Note:** Missing draft information for undrafted players is expected and should not be treated as a data quality error.

In [70]:
# Classify WR players by draft status
wr_players["draft_status"] = (
    wr_players["draft_round"]
    .apply(lambda x: "Undrafted" if pd.isna(x) else "Drafted")
)

# Count drafted vs undrafted WRs
wr_draft_status = (
    wr_players["draft_status"]
    .value_counts()
)

print(wr_draft_status)

draft_status
Drafted      76
Undrafted    30
Name: count, dtype: int64

### Final Data Profiling Summary — players.csv

**Dataset Overview**
- Total players: 510
- Unique player IDs: 510
- Duplicate records: 0
- Missing player IDs: 0

**Wide Receiver Population**
- Total WR players: 106
- Drafted WRs: 76 (71.7%)
- Undrafted WRs: 30 (28.3%)

**Data Quality Findings**
- 127 players have expected missing draft-related values because they are undrafted.
- No missing or invalid birth dates were identified.
- 14 colleges are associated with multiple conferences, potentially reflecting historical conference realignment.
- Four 2023 first-round draft records have potential pick-number inconsistencies requiring verification.

**Conclusion**

The `players.csv` dataset is suitable for proceeding to cross-table analysis, with unresolved findings documented for later investigation.

**Next Step:** Profile the next dataset and validate player-level relationships using `nfl_id`.